n1 = int(input("primeiro numero:  "))
n2 = int(input("segundo numero:  "))
n3 = int(input("terceiro numero:  "))
menor = min(n1, n2, n3)
maior = max(n1, n2, n3)
meio = (n1 + n2 + n3 - maior-menor)
print(menor)
print(meio)
print(maior)